ENDPOINT_BROWSE  = "browse"
ENDPOINT_SEARCH  = "search"
ENDPOINT_PLAYER  = "player"
ENDPOINT_NEXT    = "next"

BROWSE_ID_TRENDING = "FEtrending"

SEARCH_FILTER_LIVE     = "EgJAAQ%3D%3D"
SEARCH_FILTER_LOCATION = "EgIIAQ%3D%3D"

SORT_RELEVANCE   = None
SORT_UPLOAD_DATE = "CAISAhAB"
SORT_VIEW_COUNT  = "CAMSAhAB"
SORT_RATING      = "CAESAhAB"

CHANNEL_TAB_VIDEOS = "EgZ2aWRlb3M"

TRENDING_FILTER_NOW   = None
TRENDING_FILTER_MUSIC = "EgZtdXNpYw%3D%3D"
TRENDING_FILTER_GAMES = "EgZnYW1pbmc%3D"
TRENDING_FILTER_MOVIES = "EgZtb3ZpZXM%3D"

CLIENT_NAME    = "WEB"
CLIENT_VERSION = "2.20260603.05.00"
CLIENT_HL      = "vi"
CLIENT_GL      = "VN"

DEFAULT_TIMEOUT = 15
