_GL_TIMEZONE = {
    "VN": "Asia/Ho_Chi_Minh",
    "TH": "Asia/Bangkok",
    "ID": "Asia/Jakarta",
    "SG": "Asia/Singapore",
    "PH": "Asia/Manila",
    "MY": "Asia/Kuala_Lumpur",
    "JP": "Asia/Tokyo",
    "KR": "Asia/Seoul",
    "CN": "Asia/Shanghai",
    "IN": "Asia/Kolkata",
    "AE": "Asia/Dubai",
    "EG": "Africa/Cairo",
    "GB": "Europe/London",
    "FR": "Europe/Paris",
    "DE": "Europe/Berlin",
    "RU": "Europe/Moscow",
    "US": "America/New_York",
    "CA": "America/Toronto",
    "MX": "America/Mexico_City",
    "BR": "America/Sao_Paulo",
    "AR": "America/Argentina/Buenos_Aires",
    "NG": "Africa/Lagos",
    "ZA": "Africa/Johannesburg",
    "AU": "Australia/Sydney",
}
