"""TikTok crawler constants (pool, cache, TikHub)."""

TIKTOK_POOL_SIZE = 3
TIKTOK_NATIVE_TIMEOUT = 25.0
TIKTOK_WARM_TIMEOUT = 25.0
TIKTOK_WARM_TIMEOUT_2 = 30.0
TIKTOK_WARM_EXPLORE = 20.0
MSTOKEN_TTL = 50.0
POOL_REFRESH_INTERVAL = 600.0
TIKTOK_CACHE_TTL = 1800.0
TIKTOK_CACHE_MAX_SIZE = 500
TIKHUB_BASE_URL = "https://api.tikhub.io"
TIKHUB_TIMEOUT = 20.0
TIKHUB_MAX_CONN = 10
TIKHUB_MAX_KEEPALIVE = 5

# API / tool defaults
DEFAULT_REGION = "VN"
DEFAULT_LANGUAGE = "vi"
DEFAULT_SEARCH_COUNT = 20
